<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Rocket</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>13</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>1558.3859312334707</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>801.3041260030857</KnownMass>
                    <Density>1291.6518795422098</Density>
                    <Material>Fiberglass</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>801.3041260030857</CalcMass>
                    <CalcCG>381.88543772785135</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>609.5999999999999</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>1</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>3.175</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>156.33700000000002</BaseDia>
                    <ShoulderLen>139.7</ShoulderLen>
                    <ShoulderOD>151.765</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>1066.0657507133249</KnownMass>
                    <Density>958.7050344900001</Density>
                    <Material>Kraft phenolic</Material>
                    <Name>Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>1066.0657507133249</CalcMass>
                    <CalcCG>609.5999999999999</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>1219.1999999999998</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>2</SerialNo>
                    <OD>156.33700000000002</OD>
                    <ID>152.5778</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>152.5778</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>4000.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Payload</Name>
                            <KnownCG>380.9999999999995</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>380.9999999999995</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>300.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Parachute>
                            <KnownMass>3000.0</KnownMass>
                            <Density>0.006700000000000001</Density>
                            <Material>Ripstop nylon</Material>
                            <Name>Parachute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>5.08</Xb>
                            <CalcMass>121.63877313216533</CalcMass>
                            <CalcCG>70.0</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>140.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>4</SerialNo>
                            <Dia>1500.0</Dia>
                            <ShroudLineCount>6</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>300.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0018</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Elastic cord (round 2 mm, 1/16 in)</ShroudLineMaterial>
                            <DragCoefficient>0.8</DragCoefficient>
                        </Parachute>
                        <MassObject>
                            <KnownMass>0.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Avionics</Name>
                            <KnownCG>154.94</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>154.94</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>50.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
                <Transition>
                    <KnownMass>74.64079788974165</KnownMass>
                    <Density>950.0</Density>
                    <Material>Kraft phenolic</Material>
                    <Name>Transition</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>74.64079788974165</CalcMass>
                    <CalcCG>38.31267407072853</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>75.00000000000001</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>6</SerialNo>
                    <ShapeCode>0</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>2.0</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <FrontShoulderLen>0.0</FrontShoulderLen>
                    <RearShoulderLen>0.0</RearShoulderLen>
                    <FrontShoulderDia>0.0</FrontShoulderDia>
                    <RearShoulderDia>0.0</RearShoulderDia>
                    <FrontDia>156.33700000000002</FrontDia>
                    <RearDia>177.79999999999998</RearDia>
                </Transition>
                <BodyTube>
                    <KnownMass>4469.389779425736</KnownMass>
                    <Density>2700.0</Density>
                    <Material>Aluminum</Material>
                    <Name>Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>4469.389779425736</CalcMass>
                    <CalcCG>749.3</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>1498.6</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>7</SerialNo>
                    <OD>177.79999999999998</OD>
                    <ID>173.79999999999998</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>173.79999999999998</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <BodyTube>
                            <KnownMass>211.92194439430838</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Inner Tube #1</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>211.92194439430838</CalcMass>
                            <CalcCG>650.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>1301.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <OD>153.0</OD>
                            <ID>152.0</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>152.0</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <BodyTube>
                            <KnownMass>8.930046634991232</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Inner Tube #2</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>8.930046634991232</CalcMass>
                            <CalcCG>104.13999999999999</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>149.99999999999997</RadialLoc>
                            <RadialAngle>2.356194490192345</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>208.27999999999997</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <OD>40.64</OD>
                            <ID>39.64</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>39.64</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <BodyTube>
                            <KnownMass>8.930046634991232</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Inner Tube #3</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>8.930046634991232</CalcMass>
                            <CalcCG>104.13999999999999</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>149.99999999999997</RadialLoc>
                            <RadialAngle>0.7853981633974483</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>208.27999999999997</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>10</SerialNo>
                            <OD>40.64</OD>
                            <ID>39.64</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>39.64</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <BodyTube>
                            <KnownMass>8.930046634991232</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Inner Tube #4</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>8.930046634991232</CalcMass>
                            <CalcCG>104.13999999999999</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>149.99999999999997</RadialLoc>
                            <RadialAngle>-0.7853981633974483</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>208.27999999999997</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <OD>40.64</OD>
                            <ID>39.64</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>39.64</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <BodyTube>
                            <KnownMass>8.930046634991232</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Inner Tube #5</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>8.930046634991232</CalcMass>
                            <CalcCG>104.13999999999999</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>149.99999999999997</RadialLoc>
                            <RadialAngle>-2.356194490192345</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>208.27999999999997</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>12</SerialNo>
                            <OD>40.64</OD>
                            <ID>39.64</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>39.64</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <FinSet>
                            <KnownMass>208.94822726400005</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Trapezoidal fin set</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>208.94822726400005</CalcMass>
                            <CalcCG>107.14077097505668</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.7853981633974483</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>13</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>200.66</RootChord>
                            <TipChord>172.71999999999997</TipChord>
                            <SemiSpan>137.16</SemiSpan>
                            <SweepDistance>27.94</SweepDistance>
                            <Thickness>3.0</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>